package com.sd.tgfinger.dao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sd.tgfinger.pojo.Finger6;

import com.sd.tgfinger.dao.db.Finger6Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig finger6DaoConfig;

    private final Finger6Dao finger6Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        finger6DaoConfig = daoConfigMap.get(Finger6Dao.class).clone();
        finger6DaoConfig.initIdentityScope(type);

        finger6Dao = new Finger6Dao(finger6DaoConfig, this);

        registerDao(Finger6.class, finger6Dao);
    }
    
    public void clear() {
        finger6DaoConfig.clearIdentityScope();
    }

    public Finger6Dao getFinger6Dao() {
        return finger6Dao;
    }

}
